Repository boostcampwm-2024/web26-LICO, pull requests merged in 2024-12, with the labels that each got.

#291 [Feature]: 모니터링을 위한 인터셉터 & 필터
  Backend/apps/api/src/app.module.ts
  Backend/apps/api/src/common/filters/http-exception.filter.ts
  Backend/apps/api/src/common/interceptors/monitoring.interceptor.ts
  Backend/apps/api/src/common/middleware/request-time.middleware.ts
  Backend/apps/api/src/common/services/cloud-insight.service.ts
Labels: ✨Feature✨, BE

#292 [Fix]: 인코딩 옵션 조정(웹 스튜디오 송출 불가 문제 수정, 저장 경로 rclone마운트 디렉토리 로 변경)
  Backend/server/encoding/stream_process.sh
Labels: 🔧Config🔧, BE

#293 [Feature] : 가계정 기능 구현
  Backend/apps/api/src/auth/auth.controller.ts
  Backend/apps/api/src/auth/auth.module.ts
  Backend/apps/api/src/auth/auth.service.ts
  Backend/apps/api/src/auth/strategies/jwt.strategy.ts
  Backend/apps/api/src/auth/strategies/lico.strategy.ts
  Backend/apps/api/src/users/entity/user.entity.ts
  Backend/package-lock.json
  Backend/package.json
Labels: ✨Feature✨, BE

#295 [Feature] 채팅 팝업 모드, 타임스탬프 모드 구현, 클린 봇 수정
  Frontend/src/components/chat/ChatMessage.tsx
  Frontend/src/components/chat/ChatProfileModal.tsx
  Frontend/src/components/chat/ChatSettingsMenu.tsx
  Frontend/src/components/chat/ChatWindow.tsx
  Frontend/src/components/chat/PendingMessageNotification.tsx
  Frontend/src/hooks/chat/useChatMessages.ts
  Frontend/src/hooks/chat/useChatScroll.ts
  Frontend/src/hooks/chat/useChatSocket.ts
  Frontend/src/pages/ChatPopupPage/index.tsx
  Frontend/src/routes/index.tsx
  Frontend/src/types/live.ts
  Frontend/src/utils/format.tsx
Labels: ✨Feature✨, FE

#294 [Feature] WebStudio 기능 마무리
  Frontend/src/contexts/CanvasContext.tsx
  Frontend/src/hooks/canvas/useCanvasElement.ts
  Frontend/src/hooks/canvas/useDrawing.ts
  Frontend/src/hooks/canvas/useImage.ts
  Frontend/src/hooks/canvas/useText.ts
  Frontend/src/pages/StudioPage/DrawCanvas.tsx
  Frontend/src/pages/StudioPage/InteractionCanvas.tsx
  Frontend/src/pages/StudioPage/Modals/CamMicSetting.tsx
  Frontend/src/pages/StudioPage/Modals/CanvasElementDeleteModal.tsx
  Frontend/src/pages/StudioPage/Modals/Palette.tsx
  Frontend/src/pages/StudioPage/Modals/StreamGuide.tsx
  Frontend/src/pages/StudioPage/Modals/TextSetting.tsx
  Frontend/src/pages/StudioPage/StreamCanvas.tsx
  Frontend/src/pages/StudioPage/StreamContainer.tsx
  Frontend/src/pages/StudioPage/WebRTCStream.ts
  Frontend/src/pages/StudioPage/WebStreamControls.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/store/useStudioStore.ts
  Frontend/src/types/canvas.ts
Labels: ✨Feature✨, 🐛Fix🐛, ♻️Refactor♻️, FE

#299 [Fix] 방송 진행 중 여부 획득 API 추가 및 방송 시작 시 viewers 초기화 하도록 변경
  Backend/apps/api/src/chats/chats.service.ts
  Backend/apps/api/src/lives/lives.controller.ts
  Backend/apps/api/src/lives/lives.service.ts
Labels: 🐛Fix🐛, BE

#296 [Fix] hls.js 옵션 수정, 클린봇 버그 수정
  Frontend/src/components/chat/ChatWindow.tsx
  Frontend/src/hooks/useHls.ts
Labels: 🐛Fix🐛, FE

#297 [Feature] 팔로워 수, 카테고리 페이지 라이브와 시청자 수 api 연결
  Frontend/src/apis/follow.ts
  Frontend/src/components/category/CategoryCard/index.tsx
  Frontend/src/hooks/useFollow.ts
  Frontend/src/pages/CategoryPage/index.tsx
  Frontend/src/pages/FollowingPage/index.tsx
  Frontend/src/pages/LivePage/LiveInfo.tsx
  Frontend/src/pages/LivePage/StreamerInfo.tsx
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/StudioPage/StreamInfo.tsx
  Frontend/src/types/category.ts
Labels: ✨Feature✨, FE

#303 [Fix] 레이아웃, 라우터 관련 버그 수정, 개선
  Frontend/src/components/VideoPlayer/Control/index.tsx
  Frontend/src/components/VideoPlayer/index.tsx
  Frontend/src/components/category/CategoryCard/index.tsx
  Frontend/src/components/category/CategoryGrid/index.tsx
  Frontend/src/components/channel/ChannelCard/ChannelInfo.tsx
  Frontend/src/components/channel/ChannelCard/index.tsx
  Frontend/src/components/channel/ChannelGrid/index.tsx
  Frontend/src/components/chat/ChatHeader.tsx
  Frontend/src/components/chat/ChatWindow.tsx
  Frontend/src/components/layout/NavItem.tsx
  Frontend/src/components/layout/Navbar.tsx
  Frontend/src/components/layout/NavbarMini.tsx
  Frontend/src/hooks/useCategory.ts
  Frontend/src/hooks/useFollow.ts
  Frontend/src/hooks/useLive.ts
  Frontend/src/layouts/Layout.tsx
  Frontend/src/pages/CategoryPage/index.tsx
  Frontend/src/pages/ChatPopupPage/index.tsx
  Frontend/src/pages/HomePage/index.tsx
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/LivesPage/index.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/routes/index.tsx
  Frontend/src/store/useLayoutStore.ts
  Frontend/src/store/useViewMode.ts
Labels: 🐛Fix🐛, ♻️Refactor♻️, FE

#304 [Feature] 가계정 설정 변경 및 studio 정보 default 값 추가
  Backend/apps/api/src/auth/auth.controller.ts
  Backend/apps/api/src/auth/auth.service.ts
  Backend/apps/api/src/auth/strategies/lico.strategy.ts
  Backend/apps/api/src/auth/strategies/nickname-data.ts
  Backend/apps/api/src/follow/follow.service.ts
  Backend/apps/api/src/users/dto/create.user.dto.ts
  Backend/apps/api/src/users/users.service.ts
Labels: ✨Feature✨, BE

#302 [Fix] 각종 버그 픽스, 게스트로그인 추가
  Frontend/src/apis/auth.ts
  Frontend/src/components/category/CategoryCard/index.tsx
  Frontend/src/components/channel/ChannelCard/ChannelThumbnail.tsx
  Frontend/src/components/channel/ChannelCard/index.tsx
  Frontend/src/components/chat/ChatSettingsMenu.tsx
  Frontend/src/components/common/Badges/CategoryBadge.tsx
  Frontend/src/hooks/useAuth.ts
  Frontend/src/mocks/mockChannels.ts
  Frontend/src/pages/FollowingPage/OfflineGrid.tsx
  Frontend/src/pages/HomePage/index.tsx
  Frontend/src/pages/LoginPage/index.tsx
  Frontend/src/pages/StudioPage/Modals/CamMicSetting.tsx
  Frontend/src/pages/StudioPage/Modals/Palette.tsx
  Frontend/src/pages/StudioPage/Modals/StreamGuide.tsx
  Frontend/src/pages/StudioPage/StreamInfo.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/routes/ProtectedRoute.tsx
  Frontend/src/routes/index.tsx
  Frontend/src/store/useStudioStore.ts
Labels: bug, 🐛Fix🐛, FE

#306 [Feature] 가계정 프로필 이미지 랜덤 생성
  Backend/apps/api/src/auth/strategies/lico.strategy.ts
  Backend/apps/api/src/lives/entity/live.entity.ts
Labels: ✨Feature✨, BE

#308 [Fix] 채팅창 잠금 기능, 반응형 최소 넓이 등 레이아웃 관련 버그 수정
  Frontend/src/layouts/Layout.tsx
  Frontend/src/pages/CategoryPage/index.tsx
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/StudioPage/index.tsx
Labels: 🐛Fix🐛, FE

#311 [Feature] 방송 시작, 종료시 메세지 추가 / 로딩 딜레이 훅 구현
  Frontend/src/components/VideoPlayer/index.tsx
  Frontend/src/hooks/useCheckStream.ts
  Frontend/src/hooks/useDelayedLoading.ts
  Frontend/src/hooks/useHls.ts
  Frontend/src/pages/CategoryPage/index.tsx
  Frontend/src/pages/FollowingPage/index.tsx
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/LivesPage/index.tsx
  Frontend/src/pages/StudioPage/index.tsx
Labels: ✨Feature✨, FE

#312 [Feature] HTML meta 태그 추가, 깃 충돌 해결
  Frontend/index.html
  Frontend/public/apple-touch-icon.png
  Frontend/public/favicon.ico
  Frontend/public/og-image.png
  Frontend/src/hooks/useCheckStream.ts
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/StudioPage/index.tsx
Labels: ✨Feature✨, FE

#316 [Fix] HTML 태그 중복 문제 해결
  Frontend/index.html
Labels: 🐛Fix🐛, FE
