Repository boostcampwm-2024/web26-LICO, pull requests merged in 2024-11, with the labels that each got.

#106 [Feature] 네비게이션 바 구현
  Frontend/src/components/layout/Navbar.tsx
  Frontend/src/layouts/Layout.tsx
Labels: ✨Feature✨, FE

#108 [Fix] Navbar 라우팅 /live -> /live
  Frontend/src/components/layout/Navbar.tsx
Labels: 🐛Fix🐛, FE

#109 [Feature] 백엔드 초기 설정 추가
  Backend/.eslintrc.js
  Backend/.prettierrc
  Backend/package-lock.json
  Backend/package.json
Labels: 🚚Chore🚚

#110 [Chore] FE eslint 설정 수정
  Frontend/.eslintrc.cjs
  Frontend/eslint.config.js
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/main.tsx
  Frontend/tsconfig.node.json
Labels: 🚚Chore🚚

#112 [Feature] 기본 모듈 생성 및 환경 변수 세팅
  Backend/package-lock.json
  Backend/package.json
  Backend/src/app.module.ts
  Backend/src/auth/auth.controller.spec.ts
  Backend/src/auth/auth.controller.ts
  Backend/src/auth/auth.module.ts
  Backend/src/auth/auth.service.spec.ts
  Backend/src/auth/auth.service.ts
  Backend/src/categories/categories.controller.spec.ts
  Backend/src/categories/categories.controller.ts
  Backend/src/categories/categories.module.ts
  Backend/src/categories/categories.service.spec.ts
  Backend/src/categories/categories.service.ts
  Backend/src/main.ts
  Backend/src/streaming/streaming.controller.spec.ts
  Backend/src/streaming/streaming.controller.ts
  Backend/src/streaming/streaming.module.ts
  Backend/src/streaming/streaming.service.spec.ts
  Backend/src/streaming/streaming.service.ts
  Backend/src/users/users.controller.spec.ts
  Backend/src/users/users.controller.ts
  Backend/src/users/users.module.ts
  Backend/src/users/users.service.spec.ts
  Backend/src/users/users.service.ts
  Backend/src/videos/videos.controller.spec.ts
  Backend/src/videos/videos.controller.ts
  Backend/src/videos/videos.module.ts
  Backend/src/videos/videos.service.spec.ts
  Backend/src/videos/videos.service.ts
Labels: ✨Feature✨, BE

#113 [Feature] 페이지 및 여러 기능 구현
  Frontend/src/App.tsx
  Frontend/src/components/LiveInfo/StreamerInfo.tsx
  Frontend/src/components/LiveInfo/index.tsx
  Frontend/src/components/VideoPlayer/index.tsx
  Frontend/src/components/category/CategoryCard/index.tsx
  Frontend/src/components/category/CategoryGrid/index.tsx
  Frontend/src/components/channel/ChannelCard/ChannelInfo.tsx
  Frontend/src/components/channel/ChannelCard/ChannelThumbnail.tsx
  Frontend/src/components/channel/ChannelCard/index.tsx
  Frontend/src/components/channel/ChannelGrid/index.tsx
  Frontend/src/components/common/Badges/Badge.tsx
  Frontend/src/components/common/Badges/CategoryBadge.tsx
  Frontend/src/components/common/Buttons/FollowButton.tsx
  Frontend/src/components/common/Buttons/SortButton.tsx
  Frontend/src/components/common/LiveInfo/StreamerInfo.tsx
  Frontend/src/components/common/LiveInfo/index.tsx
  Frontend/src/contexts/ChannelContext.tsx
  Frontend/src/mocks/mockCategories.ts
  Frontend/src/mocks/mockChannels.ts
  Frontend/src/mocks/mockUsers.ts
  Frontend/src/pages/CategoryPage/CategoryDetailPage.tsx
  Frontend/src/pages/CategoryPage/index.tsx
  Frontend/src/pages/FollowingPage/index.tsx
  Frontend/src/pages/HomePage/index.tsx
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/LivesPage/index.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/routes/index.tsx
  Frontend/src/store/useStore.ts
  Frontend/src/utils/format.tsx
Labels: ✨Feature✨, FE

#114 [Feature] 채팅창 UI 구현
  Frontend/src/components/chat/ChatHeader.tsx
  Frontend/src/components/chat/ChatInput.tsx
  Frontend/src/components/chat/ChatMessage.tsx
  Frontend/src/components/chat/ChatWindow.tsx
  Frontend/src/components/chat/constants.ts
  Frontend/src/components/chat/utils.ts
  Frontend/src/mocks/mockMessages.ts
Labels: ✨Feature✨, FE

#115 [Fix] 배포 위한 빌드 오류 수정
  Frontend/src/components/VideoPlayer/index.tsx
  Frontend/src/pages/StudioPage/index.tsx
Labels: bug, 🐛Fix🐛

#123 [Feature] StudioPage UI 구현
  Frontend/src/components/layout/Navbar.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/routes/index.tsx
Labels: ✨Feature✨, FE

#124 [Feature] OAuth 구현(github, google, naver)
  Backend/package-lock.json
  Backend/package.json
  Backend/src/auth/auth.controller.ts
  Backend/src/auth/auth.module.ts
  Backend/src/auth/auth.service.ts
  Backend/src/auth/strategies/github.strategy.ts
  Backend/src/auth/strategies/google.strategy.ts
  Backend/src/auth/strategies/naver.strategy.ts
  Backend/src/main.ts
Labels: ✨Feature✨, BE

#125 [Feature] LivePage 동적 레이아웃 & 채팅 컴포넌트 구현
  Frontend/src/components/LiveInfo/StreamerInfo.tsx
  Frontend/src/components/LiveInfo/index.tsx
  Frontend/src/components/VideoPlayer/index.tsx
  Frontend/src/components/chat/ChatHeader.tsx
  Frontend/src/components/chat/ChatMessage.tsx
  Frontend/src/components/chat/ChatWindow.tsx
  Frontend/src/components/common/Buttons/ChatOpenButton.tsx
  Frontend/src/components/layout/Navbar.tsx
  Frontend/src/components/layout/NavbarMini.tsx
  Frontend/src/hooks/useMediaQuery.ts
  Frontend/src/layouts/Layout.tsx
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/store/useLayoutStore.ts
  Frontend/tsconfig.app.json
  Frontend/vite.config.ts
Labels: ✨Feature✨, FE

#127 [Fix] 배포 페이지에서 StudioPage 404 오류 해결
  Frontend/src/components/layout/Navbar.tsx
Labels: 🐛Fix🐛

#128 [Fix] 배포 페이지에서 StudioPage 404 오류 해결
  Frontend/netlify.toml
Labels: 🐛Fix🐛

#130 [Refactor] 컴포넌트 분리, 버그 수정
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/VideoPlayer/Control/SettingsControl.tsx
  Frontend/src/components/VideoPlayer/Control/VolumeControl.tsx
  Frontend/src/components/VideoPlayer/Control/index.tsx
  Frontend/src/components/VideoPlayer/index.tsx
  Frontend/src/components/chat/ChatInput.tsx
  Frontend/src/components/chat/ChatWindow.tsx
  Frontend/src/components/common/Buttons/ChatOpenButton.tsx
  Frontend/src/components/common/Buttons/FollowButton.tsx
  Frontend/src/constants/chat/color.ts
  Frontend/src/constants/chat/input.ts
  Frontend/src/layouts/Layout.tsx
  Frontend/src/pages/FollowingPage/index.tsx
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/StudioPage/ControlButton.tsx
  Frontend/src/pages/StudioPage/StreamInfo.tsx
  Frontend/src/pages/StudioPage/StreamSettings.tsx
  Frontend/src/pages/StudioPage/WebStreamControls.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/store/useFollowStore.ts
  Frontend/src/utils/chatUtils.ts
  Frontend/tailwind.config.js
Labels: ♻️Refactor♻️, FE

#131 [Feature] api 연동
  Frontend/.gitignore
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/apis/axios.ts
  Frontend/src/apis/category.ts
  Frontend/src/apis/live.ts
  Frontend/src/assets/fonts/Pretendard-Bold.woff2
  Frontend/src/assets/fonts/Pretendard-Medium.woff2
  Frontend/src/components/LiveInfo/StreamerInfo.tsx
  Frontend/src/components/LiveInfo/index.tsx
  Frontend/src/components/category/CategoryCard/index.tsx
  Frontend/src/components/channel/ChannelCard/ChannelInfo.tsx
  Frontend/src/components/channel/ChannelCard/index.tsx
  Frontend/src/components/common/Badges/Badge.tsx
  Frontend/src/components/common/Badges/CategoryBadge.tsx
  Frontend/src/components/common/Buttons/FollowButton.tsx
  Frontend/src/components/common/Buttons/LiveStartButton.tsx
  Frontend/src/components/common/Buttons/LoginButton.tsx
  Frontend/src/components/common/Buttons/SortButton.tsx
  Frontend/src/components/layout/Navbar.tsx
  Frontend/src/components/layout/NavbarMini.tsx
  Frontend/src/config/env.ts
  Frontend/src/config/queryClient.ts
  Frontend/src/contexts/ChannelContext.tsx
  Frontend/src/hooks/useCategory.ts
  Frontend/src/hooks/useLive.ts
  Frontend/src/pages/CategoryPage/CategoryDetailPage.tsx
  Frontend/src/pages/CategoryPage/index.tsx
  Frontend/src/pages/HomePage/index.tsx
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/LivesPage/index.tsx
  Frontend/src/store/useSortStore.ts
  Frontend/src/types/category.ts
  Frontend/src/types/live.ts
  Frontend/tsconfig.app.json
  Frontend/vite.config.ts
Labels: ✨Feature✨, FE

#132 [Fix] mockdata에서 서버에서 받아온 데이터 변경으로 생기는 변경사항 및 충돌
  Frontend/package-lock.json
  Frontend/src/pages/LivePage/index.tsx
Labels: 🐛Fix🐛, FE

#152 [Feature] OAuth 를 통한 회원가입 및 로그인 구현
  Backend/package-lock.json
  Backend/package.json
  Backend/src/auth/auth.controller.ts
  Backend/src/auth/auth.module.ts
  Backend/src/auth/auth.service.ts
  Backend/src/auth/guards/jwt-auth.guard.ts
  Backend/src/auth/strategies/github.strategy.ts
  Backend/src/auth/strategies/google.strategy.ts
  Backend/src/auth/strategies/jwt.strategy.ts
  Backend/src/auth/strategies/naver.strategy.ts
  Backend/src/config/typeorm.config.ts
  Backend/src/lives/entity/live.entity.ts
  Backend/src/users/dto/create.user.dto.ts
  Backend/src/users/users.controller.ts
  Backend/src/users/users.module.ts
  Backend/src/users/users.service.ts
Labels: ✨Feature✨, BE

#153 [Feature] 라이브 방송 시작,종료 알림 API 및 채널ID 획득 API 추가(서버용)
  Backend/src/lives/dto/live.dto.ts
  Backend/src/lives/dto/lives.dto.ts
  Backend/src/lives/entity/live.entity.ts
  Backend/src/lives/lives.controller.ts
  Backend/src/lives/lives.service.spec.ts
  Backend/src/lives/lives.service.ts
Labels: ✨Feature✨, BE

#154 [Feature] OAuth 소셜로그인 구현
  Frontend/src/apis/axios.ts
  Frontend/src/assets/icons/socialLoginIcons.tsx
  Frontend/src/components/chat/ChatMessage.tsx
  Frontend/src/components/layout/Navbar.tsx
  Frontend/src/components/layout/NavbarMini.tsx
  Frontend/src/config/env.ts
  Frontend/src/hooks/useAuth.ts
  Frontend/src/pages/LoginPage/LoginCallback.tsx
  Frontend/src/pages/LoginPage/index.tsx
  Frontend/src/routes/ProtectedRoute.tsx
  Frontend/src/routes/index.tsx
  Frontend/src/store/useAuthStore.ts
Labels: ✨Feature✨, FE

#157 [Fix] 환경 변수에 SERVER_URL 추가, callback URL 변경
  Backend/package-lock.json
  Backend/package.json
  Backend/src/auth/auth.controller.spec.ts
  Backend/src/auth/auth.service.spec.ts
  Backend/src/auth/auth.service.ts
  Backend/src/auth/strategies/github.strategy.ts
  Backend/src/auth/strategies/google.strategy.ts
  Backend/src/auth/strategies/naver.strategy.ts
  Backend/src/users/users.service.ts
Labels: 🐛Fix🐛, BE

#161 [Config] cors 및 쿠키 설정 변경
  Backend/src/auth/auth.controller.ts
  Backend/src/auth/auth.service.spec.ts
  Backend/src/main.ts
Labels: 🔧Config🔧, BE

#163 [Fix] github oauth 스코프 변경
  Backend/src/auth/auth.controller.ts
  Backend/src/auth/strategies/github.strategy.ts
Labels: bug, BE

#166 [Fix]: live_id 값이 null이 되는 거 수정
  Backend/src/auth/strategies/github.strategy.ts
  Backend/src/users/users.service.ts
Labels: 🐛Fix🐛, BE

#167 [Feature] useHls 기능 추가, 로딩 컴포넌트 구현, 방송 시간 계산 컴포넌트 추가
  Frontend/src/components/LiveInfo/StreamingTimer.tsx
  Frontend/src/components/LiveInfo/index.tsx
  Frontend/src/components/VideoPlayer/LoadingSpinner.tsx
  Frontend/src/components/VideoPlayer/index.tsx
  Frontend/src/components/VideoPlayer/useHls.ts
  Frontend/src/hooks/useHls.ts
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/styles/index.css
Labels: ✨Feature✨, FE

#168 [Feature] jwt를 쿠키 방식이 아닌 헤더 방식으로 변경
  Backend/src/auth/auth.controller.ts
  Backend/src/auth/strategies/jwt.strategy.ts
  Backend/src/main.ts
Labels: ✨Feature✨, BE

#171 [Feature] 화질 설정 구현, LivePage 수정
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/LiveInfo/index.tsx
  Frontend/src/components/VideoPlayer/Control/SettingsControl.tsx
  Frontend/src/components/VideoPlayer/Control/index.tsx
  Frontend/src/components/VideoPlayer/index.tsx
  Frontend/src/components/common/LoadingSpinner.tsx
  Frontend/src/hooks/useHls.ts
  Frontend/src/layouts/Layout.tsx
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/types/hlsQuality.ts
  Frontend/vite.config.ts
Labels: ✨Feature✨, FE

#175 [Feature] google OAuth accessToken, refreshToken 생성
  Backend/src/app.module.ts
  Backend/src/auth/auth.controller.ts
  Backend/src/auth/auth.module.ts
  Backend/src/auth/auth.service.ts
  Backend/src/auth/strategies/github.strategy.ts
  Backend/src/auth/strategies/google.strategy.ts
  Backend/src/auth/strategies/jwt.strategy.ts
  Backend/src/auth/strategies/naver.strategy.ts
  Backend/src/main.ts
  Backend/src/users/dto/create.user.dto.ts
  Backend/src/users/entity/user.entity.ts
  Backend/src/users/users.module.ts
  Backend/src/users/users.service.ts
  Frontend/src/store/useAuthStore.ts
Labels: ✨Feature✨, BE

#182 [Fix] google Oauth 디버깅
  Backend/src/auth/strategies/google.strategy.ts
Labels: 🐛Fix🐛, BE

#177 [Feature] LivePage Oneline/Offline에 따른 변화 구현, channelContext 제거
  Frontend/src/App.tsx
  Frontend/src/assets/images/offline.gif
  Frontend/src/components/LiveInfo/StreamerInfo.tsx
  Frontend/src/components/LiveInfo/index.tsx
  Frontend/src/components/VideoPlayer/OfflinePlayer.tsx
  Frontend/src/components/VideoPlayer/index.tsx
  Frontend/src/components/channel/ChannelCard/ChannelThumbnail.tsx
  Frontend/src/components/channel/ChannelCard/index.tsx
  Frontend/src/components/error/NotFound.tsx
  Frontend/src/contexts/ChannelContext.tsx
  Frontend/src/hooks/useCategory.ts
  Frontend/src/hooks/useLive.ts
  Frontend/src/pages/FollowingPage/index.tsx
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/types/live.ts
Labels: ✨Feature✨, FE

#188 [Feature] 채팅 기능 코드 추가
  Backend/package-lock.json
  Backend/package.json
  Backend/server/encoding/cleanup.sh
  Backend/src/app.module.ts
  Backend/src/chats/chats.gateway.spec.ts
  Backend/src/chats/chats.gateway.ts
  Backend/src/chats/chats.module.ts
  Backend/src/chats/chats.service.spec.ts
  Backend/src/chats/chats.service.ts
  Backend/src/config/redis.config.ts
  Backend/src/lives/lives.controller.ts
  Backend/src/lives/lives.module.ts
  Backend/src/lives/lives.service.ts
  Backend/src/main.ts
Labels: ✨Feature✨, BE

#189 [Feature] auth/refresh api 구현
  Backend/src/auth/auth.controller.ts
  Backend/src/auth/auth.service.ts
  Backend/src/users/dto/create.user.dto.ts
  Backend/src/users/users.service.ts
Labels: ✨Feature✨, BE

#194 [Feature] 스튜디오 페이지 기능 개발
  Frontend/src/apis/live.ts
  Frontend/src/components/chat/ChatWindow.tsx
  Frontend/src/components/common/Dropdown/index.tsx
  Frontend/src/components/common/LoadingSpinner/index.tsx
  Frontend/src/components/common/SearchInput/index.tsx
  Frontend/src/components/common/Toast/index.tsx
  Frontend/src/components/layout/Navbar.tsx
  Frontend/src/components/layout/NavbarMini.tsx
  Frontend/src/constants/categories.ts
  Frontend/src/hooks/useClickOutside.ts
  Frontend/src/hooks/useDebounce.ts
  Frontend/src/hooks/useLive.ts
  Frontend/src/hooks/useSearch.ts
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/StudioPage/StreamInfo.tsx
  Frontend/src/pages/StudioPage/StreamSettings.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/routes/index.tsx
  Frontend/src/store/useAuthStore.ts
  Frontend/src/types/live.ts
Labels: ✨Feature✨, FE

#197 [Feature] 마이페이지, 유저 정보 수정
  Frontend/src/apis/user.ts
  Frontend/src/components/common/Toast/index.tsx
  Frontend/src/components/layout/Navbar.tsx
  Frontend/src/components/layout/NavbarMini.tsx
  Frontend/src/hooks/useUser.ts
  Frontend/src/pages/MyPage/index.tsx
  Frontend/src/routes/index.tsx
  Frontend/src/types/user.ts
Labels: ✨Feature✨, FE

#199 [Feature] IS_PRODUCTION 환경 변수로 cookie 관리
  Backend/src/auth/auth.controller.ts
Labels: ✨Feature✨, BE

#206 [Feature] 채팅 기능 서버 코드 수정
  Backend/src/auth/guards/websocket-auth.guard.ts
  Backend/src/auth/strategies/websocket.strategy.ts
  Backend/src/chats/chats.gateway.ts
  Backend/src/chats/chats.middleware.spec.ts
  Backend/src/chats/chats.middleware.ts
  Backend/src/chats/chats.module.ts
  Backend/src/chats/chats.service.ts
  Backend/src/lives/lives.controller.ts
Labels: ✨Feature✨, BE

#205 [Feature] 유저 프로필 업로드 api
  Backend/package-lock.json
  Backend/package.json
  Backend/src/auth/auth.controller.ts
  Backend/src/users/users.controller.ts
  Backend/src/users/users.service.ts
Labels: ✨Feature✨, BE

#207 [Fix] 각종 변경 및 버그 수정
  Frontend/src/apis/axios.ts
  Frontend/src/apis/live.ts
  Frontend/src/components/layout/Navbar.tsx
  Frontend/src/components/layout/NavbarMini.tsx
  Frontend/src/hooks/useLive.ts
  Frontend/src/mocks/mockChannels.ts
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/StudioPage/ControlButton.tsx
  Frontend/src/pages/StudioPage/StreamInfo.tsx
  Frontend/src/pages/StudioPage/StreamSettings.tsx
  Frontend/src/pages/StudioPage/WebStreamControls.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/routes/index.tsx
Labels: 🐛Fix🐛, FE

#212 [Feature] follow-api 생성
  Backend/src/app.module.ts
  Backend/src/follow/follow.controller.spec.ts
  Backend/src/follow/follow.controller.ts
  Backend/src/follow/follow.module.ts
  Backend/src/follow/follow.service.spec.ts
  Backend/src/follow/follow.service.ts
  Backend/src/users/dto/create.user.dto.ts
  Backend/src/users/entity/user.entity.ts
Labels: ✨Feature✨, BE

#214 [Config] 인코딩 설정 변경
  Backend/server/encoding/cleanup.sh
  Backend/server/encoding/nginx.conf
  Backend/server/encoding/stream_process.sh
Labels: 🔧Config🔧, BE

#220 [Feature] 팔로우 기능 구현
  Frontend/src/apis/follow.ts
  Frontend/src/components/channel/ChannelCard/index.tsx
  Frontend/src/components/common/Buttons/FollowButton.tsx
  Frontend/src/hooks/useFollow.ts
  Frontend/src/pages/FollowingPage/OfflineCard.tsx
  Frontend/src/pages/FollowingPage/OfflineGrid.tsx
  Frontend/src/pages/FollowingPage/index.tsx
  Frontend/src/pages/LivePage/LiveInfo.tsx
  Frontend/src/pages/LivePage/StreamerInfo.tsx
  Frontend/src/pages/LivePage/StreamingTimer.tsx
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/StudioPage/StreamSettings.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/store/useFollowStore.ts
  Frontend/src/types/live.ts
Labels: ✨Feature✨, FE

#221 [Feature] lives-api 파라미터 응답 추가
  Backend/src/categories/categories.controller.ts
  Backend/src/lives/lives.controller.ts
  Backend/src/lives/lives.service.ts
Labels: ✨Feature✨, BE

#222 [Feature] 채팅방 웹소켓 연결 및 기능 구현
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/apis/user.ts
  Frontend/src/components/chat/ChatInput.tsx
  Frontend/src/components/chat/ChatMessage.tsx
  Frontend/src/components/chat/ChatProfileModal.tsx
  Frontend/src/components/chat/ChatWindow.tsx
  Frontend/src/components/chat/PendingMessageNotification.tsx
  Frontend/src/hooks/useLive.ts
  Frontend/src/hooks/useUser.ts
  Frontend/src/mocks/mockMessages.ts
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/types/live.ts
Labels: ✨Feature✨, FE

#234 [Fix] : 라이브 상세 정보 조회에 streamerId를 추가
  Backend/src/lives/dto/live.dto.ts
  Backend/src/lives/entity/live.entity.ts
Labels: 🐛Fix🐛, BE

#235 [Fix] 채널 id 대신 스트리머 id로 팔로우
  Frontend/src/apis/follow.ts
  Frontend/src/components/common/Buttons/FollowButton.tsx
  Frontend/src/hooks/useFollow.ts
  Frontend/src/pages/LivePage/LiveInfo.tsx
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/types/live.ts
Labels: bug, 🐛Fix🐛, FE

#236 [Fix] lives 에도 streamerId 추가
  Backend/src/lives/dto/lives.dto.ts
  Backend/src/lives/entity/live.entity.ts
Labels: bug, 🐛Fix🐛, BE

#237 [Fix] 채팅 연결 auth 수정
  Frontend/src/components/chat/ChatWindow.tsx
Labels: bug, 🐛Fix🐛

#238 [Fix] 버튼 상태 바뀌도록
  Frontend/src/apis/follow.ts
  Frontend/src/hooks/useFollow.ts
  Frontend/src/pages/FollowingPage/OfflineCard.tsx
Labels: bug, 🐛Fix🐛, FE

#246 [Fix] 카테고리 페이지에 채널 안나오는 오류 해결
  Frontend/src/apis/category.ts
  Frontend/src/components/channel/ChannelCard/ChannelInfo.tsx
  Frontend/src/components/channel/ChannelCard/index.tsx
  Frontend/src/components/common/Badges/CategoryBadge.tsx
  Frontend/src/hooks/useCategory.ts
  Frontend/src/mocks/mockCategories.ts
  Frontend/src/mocks/mockUsers.ts
  Frontend/src/pages/CategoryPage/CategoryDetailPage.tsx
  Frontend/src/types/category.ts
Labels: 🐛Fix🐛, FE

#243 [CI/CD] dev api 서버 깃헙 액션 배포 워크플로우 및 배포 스크립트 추가
  .github/workflows/develop-deploy.yml
  Backend/server/api/deploy.sh
  Backend/src/config/typeorm.config.ts
Labels: 🔧Config🔧, BE

#242 [Feature] 인기순 파라미터 구현
  Backend/src/lives/lives.controller.ts
  Backend/src/lives/lives.service.ts
  Backend/src/main.ts
Labels: ✨Feature✨, BE

#244 [Fix] 인증 절차 소켓 연결 시에만 수행되도록 변경, 챗기록 리사이즈 횟수 줄임
  Backend/src/chats/chats.gateway.ts
  Backend/src/chats/chats.middleware.spec.ts
  Backend/src/chats/chats.middleware.ts
Labels: 🐛Fix🐛, BE

#245 [Feature] LivePage(방송목록) 기능 구현 - 썸네일, Hover 등
  Frontend/src/components/channel/ChannelCard/ChannelThumbnail.tsx
  Frontend/src/components/channel/ChannelCard/ChannelThumbnailPlaceholder.tsx
  Frontend/src/components/channel/ChannelCard/HoverPreviewPlayer.tsx
  Frontend/src/components/channel/ChannelCard/index.tsx
  Frontend/src/hooks/useHls.ts
  Frontend/src/pages/LivesPage/index.tsx
  Frontend/src/types/live.ts
Labels: ✨Feature✨, FE

#249 [Config] 인코딩 설정 변경하여 CPU 부하 감소 및 인코딩 속도 증가
  Backend/server/encoding/stream_process.sh
Labels: 🔧Config🔧, BE

#251 [Refactor] 채팅 리스트 리사이즈 함수 제거
  Backend/src/chats/chats.gateway.ts
Labels: ♻️Refactor♻️, BE

#252 [Feature] 카테고리 api 시청자 수, 방송 수 추가
  Backend/src/categories/categories.service.ts
  Backend/src/categories/dto/categories.dto.ts
  Backend/src/categories/dto/category.dto.ts
  Backend/src/lives/lives.service.ts
Labels: ✨Feature✨, BE

#253 [Feature] WebStudio 구현
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/hooks/useCanvasElement.ts
  Frontend/src/pages/StudioPage/ControlButton.tsx
  Frontend/src/pages/StudioPage/Modals/CamMicSetting.tsx
  Frontend/src/pages/StudioPage/StreamContainer.tsx
  Frontend/src/pages/StudioPage/StreamInfo.tsx
  Frontend/src/pages/StudioPage/WebRTCStream.ts
  Frontend/src/pages/StudioPage/WebStreamControls.tsx
  Frontend/src/pages/StudioPage/index.tsx
Labels: ✨Feature✨, FE

#259 [Feature] WHIP 연결 형식 맞추기
  Frontend/src/pages/StudioPage/WebRTCStream.ts
  Frontend/src/pages/StudioPage/index.tsx
Labels: ✨Feature✨, FE

#260 [Feature] LivePage 방송정보 업데이트, 비디오 플레이어 개선
  Frontend/src/apis/live.ts
  Frontend/src/components/VideoPlayer/Control/SettingsControl.tsx
  Frontend/src/components/VideoPlayer/Control/VolumeControl.tsx
  Frontend/src/components/VideoPlayer/Control/index.tsx
  Frontend/src/components/VideoPlayer/index.tsx
  Frontend/src/components/channel/ChannelCard/ChannelThumbnail.tsx
  Frontend/src/components/channel/ChannelCard/ThumbnailSkeleton.tsx
  Frontend/src/components/common/Badges/Badge.tsx
  Frontend/src/hooks/useHls.ts
  Frontend/src/hooks/useLive.ts
  Frontend/src/pages/LivePage/index.tsx
  Frontend/src/pages/LivesPage/index.tsx
  Frontend/src/types/live.ts
Labels: ✨Feature✨, FE

#262 [Test] auth, users, follow, categories 테스트 코드 수정
  Backend/src/auth/auth.controller.spec.ts
  Backend/src/auth/auth.service.spec.ts
  Backend/src/auth/auth.service.ts
  Backend/src/categories/categories.controller.spec.ts
  Backend/src/categories/categories.service.spec.ts
  Backend/src/follow/follow.controller.spec.ts
  Backend/src/follow/follow.service.spec.ts
  Backend/src/users/users.controller.spec.ts
  Backend/src/users/users.service.spec.ts
Labels: ✅Test✅, BE

#267 [Refactor] WebStudio 리팩토링
  Frontend/src/config/env.ts
  Frontend/src/hooks/useCanvasElement.ts
  Frontend/src/pages/StudioPage/StreamContainer.tsx
  Frontend/src/pages/StudioPage/StreamSettings.tsx
  Frontend/src/pages/StudioPage/WebRTCStream.ts
  Frontend/src/pages/StudioPage/WebStreamControls.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/types/canvas.ts
Labels: ♻️Refactor♻️, FE

#266 [Fix] 4주차 피드백 적용, 수정
  Frontend/src/components/chat/ChatInput.tsx
  Frontend/src/pages/CategoryPage/CategoryDetailPage.tsx
  Frontend/src/pages/FollowingPage/index.tsx
Labels: 🐛Fix🐛, FE

#275 [Feature] 스트리머 팔로우 수 조회 API
  Backend/apps/api/src/follow/follow.controller.ts
  Backend/apps/api/src/follow/follow.service.ts
  Backend/apps/api/src/users/entity/user.entity.ts
Labels: ✨Feature✨, BE

#276 [Feature] 클로바 스튜디오를 이용한 채팅 필터 추가
  Backend/apps/api/src/chats/chats.module.ts
  Backend/apps/api/src/chats/chats.service.ts
  Backend/apps/api/src/main.ts
  Backend/apps/chats/src/dto/chat.dto.ts
  Backend/package-lock.json
  Backend/package.json
Labels: ✨Feature✨, BE

#277 [Config] 방송 송출 종료 5초 후 방종 처리되도록 스크립트 변경
  Backend/apps/api/src/lives/lives.controller.ts
  Backend/apps/api/src/lives/lives.service.ts
  Backend/server/encoding/cleanup.sh
  Backend/server/encoding/nginx.conf
  Backend/server/encoding/stream_process.sh
Labels: 🐛Fix🐛, 🔧Config🔧, BE

#278 [Feature] logging을 위한 winston 세팅
  Backend/apps/api/src/app.module.ts
  Backend/apps/api/src/auth/guards/jwt-auth.guard.ts
  Backend/apps/api/src/config/logger.config.ts
  Backend/apps/api/src/main.ts
Labels: ✨Feature✨, FE

#279 [Feature] WebStudio 그리기, 지우개, 텍스트
  Frontend/src/apis/live.ts
  Frontend/src/assets/icons/eraserCursor.svg
  Frontend/src/assets/icons/pencilCursor.svg
  Frontend/src/hooks/useDrawing.ts
  Frontend/src/hooks/useLive.ts
  Frontend/src/hooks/useText.ts
  Frontend/src/pages/StudioPage/Modals/Palette.tsx
  Frontend/src/pages/StudioPage/Modals/TextSetting.tsx
  Frontend/src/pages/StudioPage/StreamContainer.tsx
  Frontend/src/pages/StudioPage/WebRTCStream.ts
  Frontend/src/pages/StudioPage/WebStreamControls.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/styles/index.css
  Frontend/src/types/canvas.ts
Labels: ✨Feature✨, FE

#280 [Feature] 무한 스크롤 구현
  Frontend/src/apis/category.ts
  Frontend/src/apis/live.ts
  Frontend/src/hooks/useCategory.ts
  Frontend/src/hooks/useLive.ts
  Frontend/src/pages/CategoryPage/CategoryDetailPage.tsx
  Frontend/src/pages/LivesPage/index.tsx
  Frontend/src/types/live.ts
Labels: ✨Feature✨, FE

#281 [Fix] 채팅 필터 적용에 따른 지연 문제 수정
  Backend/apps/api/src/chats/chats.controller.ts
  Backend/apps/api/src/chats/chats.service.ts
  Backend/apps/chats/src/chats.gateway.ts
Labels: 🐛Fix🐛, BE

#284 [Feature] WebStudio
  Frontend/src/contexts/CanvasContext.tsx
  Frontend/src/hooks/canvas/useCanvasElement.ts
  Frontend/src/hooks/canvas/useDrawing.ts
  Frontend/src/hooks/canvas/useImage.ts
  Frontend/src/hooks/canvas/useText.ts
  Frontend/src/pages/StudioPage/DrawCanvas.tsx
  Frontend/src/pages/StudioPage/Modals/CanvasElementDeleteModal.tsx
  Frontend/src/pages/StudioPage/StreamCanvas.tsx
  Frontend/src/pages/StudioPage/StreamContainer.tsx
  Frontend/src/pages/StudioPage/WebStreamControls.tsx
  Frontend/src/pages/StudioPage/index.tsx
  Frontend/src/types/canvas.ts
  Frontend/vite.config.ts
Labels: ✨Feature✨, FE

#283 [Fix] chat 발송 Post로 변경
  Frontend/src/apis/chat.ts
  Frontend/src/components/chat/ChatWindow.tsx
  Frontend/src/config/env.ts
Labels: 🐛Fix🐛, FE

#282 [Feature] 로깅 인터셉터와 필터 적용
  Backend/apps/api/src/app.module.ts
  Backend/apps/api/src/common/filters/http-exception.filter.ts
  Backend/apps/api/src/common/interceptors/logging.interceptor.ts
  Backend/apps/api/src/config/logger.config.ts
  Backend/apps/api/src/follow/follow.service.ts
  Backend/package-lock.json
  Backend/package.json
Labels: ✨Feature✨, BE

#286 [Feature] 채팅 클린봇 모드 구현
  Frontend/src/components/chat/ChatHeader.tsx
  Frontend/src/components/chat/ChatMessage.tsx
  Frontend/src/components/chat/ChatSettingsMenu.tsx
  Frontend/src/components/chat/ChatWindow.tsx
  Frontend/src/components/common/Toggle/index.tsx
  Frontend/src/types/live.ts
Labels: ✨Feature✨, FE

#285 [Fix] oldchats가 2중배열로 전달되는 문제 수정
  Backend/apps/chats/src/chats.gateway.ts
Labels: 🐛Fix🐛, BE
